# Cloud Build configuration for AltayarVIP Backend
# Triggered on push to main branch

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/altayarvip-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/altayarvip-backend:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/altayarvip-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/altayarvip-backend:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'altayarvip-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/altayarvip-backend:$COMMIT_SHA'
      - '--region'
      - 'me-central1'  # Middle East (Qatar) - closest to Egypt
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-cloudsql-instances'
      - '$PROJECT_ID:me-central1:altayarvip-db'
      - '--update-secrets'
      - 'DATABASE_URL=altayarvip-database-url:latest,JWT_SECRET_KEY=altayarvip-jwt-secret:latest,FAWATERK_API_KEY=altayarvip-fawaterk-api-key:latest,FAWATERK_VENDOR_KEY=altayarvip-fawaterk-vendor-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/altayarvip-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/altayarvip-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
